### ISSUE TITLE
self closing tags aren't properly highlighted

### ISSUE THREAD

**Issue by ha404** [bassu/solarized-dark-bold-syntax#4] opened 2016-08-23 22:44 UTC
![screen shot 2016-08-23 at 3 43 27 pm](https://cloud.githubusercontent.com/assets/567126/17912446/6a2b2632-6948-11e6-8176-80abad0fb85e.png)

**Comment by bassu** [comment] 2016-08-23 23:07
The `div` is not a self-closing tag. 
And even if there's problem with other self closing tags, it would not be caused by a theme.

**Comment by ha404** [comment] 2016-08-23 23:09
@bassu in jsx `div` can be self-closing: https://facebook.github.io/react/tips/self-closing-tag.html. But you're right, it's a problem with the core.

**Closed as completed** 2016-08-23 23:11 UTC
